version: "3.1"

services:
  nodejs:
    image: "node:14"
    user: "node"
    working_dir: /app
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: npm install